version: '3.9'

services:
  front_end_app:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
      args:
        VITE_EXPRESS_JS_REST_API_URL: localhost
        VITE_KC_ADMIN_CONSOLE_API_URL: localhost
        VITE_KC_ADMIN_CONSOLE_PORT: 8443
        VITE_KC_ADMIN_CONSOLE_REALM: HTTPS_localhost_realm
        VITE_KC_ADMIN_CONSOLE_CLIENT_ID: https_localhost_client_id
    image: "front_end_kc_img:v1.0"
    container_name: front_end_kc # Matches the hostname in Central Proxy
    
    env_file:
      - .env
    networks:
      - kc_shared_central_nginx_proxy_network

networks:
  kc_shared_central_nginx_proxy_network:
    external: true