FROM ubuntu/nginx

EXPOSE 80 443
WORKDIR /app

COPY ./dist /var/www/html

RUN apt update -y && \
    apt install vim -y && \
    apt install -y iputils-ping

RUN rm -f /etc/nginx/sites-enabled/default
# COPY ./nginx/config/default /etc/nginx/sites-available/


COPY ./nginx/config/default /etc/nginx/sites-enabled/default
COPY ./nginx/config/nginx.conf /etc/nginx/

