version: '3.9'

services:
  front_end_app:
    image: "front_end_kc_img:v1.0"
    container_name: front_end_kc # Matches the hostname in Central Proxy
    
    env_file:
      - .env
    networks:
      - kc_shared_central_nginx_proxy_network

networks:
  kc_shared_central_nginx_proxy_network:
    external: true